# Read the documentation at https://github.com/thephpleague/flysystem-bundle/blob/master/docs/1-getting-started.md
flysystem:
    storages:
        private.storage: # ce nom est arbitraire
            adapter: 'local'
            options:
                # Le dossier /var est parfait pour cet usage
                directory: '%kernel.project_dir%/var/uploads'

        default.storage: # ce nom est arbitraire
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/public'

        # Je peux créer plusieurs lieux de storages
        upload.storage:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/public/uploads'



